In [2]:
import numpy as np
np.__version__

'2.3.1'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [6]:
l = [1,2,3,4,5]


In [11]:
np.array(l)


array([1, 2, 3, 4, 5])

In [12]:
arr=np.array(l)
type(arr)

numpy.ndarray

In [13]:
l = [1,2,3,4,5,"Pwskills"] # as ndarray takes only row, hence creating homogenous by itself
np.array(l)

array(['1', '2', '3', '4', '5', 'Pwskills'], dtype='<U21')

In [15]:
arr1 = np.array([[1,2,3],[4,5,6]]) #syntax
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr1.ndim # it gives dimension number

2

In [17]:
np.matrix([1,2,3,4]) # matrix is specialized two dim array

matrix([[1, 2, 3, 4]])

In [18]:
# mora ways to array
lis = [20,30,10,100]
np.asarray(lis)

array([ 20,  30,  10, 100])

In [20]:
# another way 
np.asanyarray([1,2,3,])

array([1, 2, 3])

In [28]:
# multiple approach to array
arr2 = np.fromfunction(lambda i,j: i==j, (3,3)) # construct a numpy array from function
arr2

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)

2
(3, 3)
9


In [34]:
str = "Pinki, Sheela, Friends"
print(str.split(","))
np.array(str.split(","))

['Pinki', ' Sheela', ' Friends']


array(['Pinki', ' Sheela', ' Friends'], dtype='<U8')

In [36]:
# another method of Numpy to generate a sequence of number

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [45]:
np.zeros((2,3,4)) # 2 is shape

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])